services:
  node:
    container_name: node_server
    build:
      context: .
      dockerfile: serverdockerfile
    restart: unless-stopped
    ports:
      # - "${PORT}:${PORT}/tcp"
      - "4321:${PORT}/tcp"
    
    networks:
      - server-network
  nginx:
    container_name: nginx_server
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl
      - /etc/letsencrypt:/etc/letsencrypt

    depends_on:
      - node
    networks:
      - server-network

networks:
  server-network:
    driver: bridge